services:
  redis:
    image: redis:7
    container_name: student_activity_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student_activity_backend
    ports:
      - "8000:5000"  # Host:Container - using 8000 to avoid Windows port 5000 reservation
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      PORT: 5000
      HOST: 0.0.0.0
      MONGO_URL: mongodb+srv://harhsasrinatth5599:harsha5599@cluster0.4uagd3j.mongodb.net/
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKER_CONCURRENCY: 8
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: student_activity_worker
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb+srv://harhsasrinatth5599:harsha5599@cluster0.4uagd3j.mongodb.net/
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKER_CONCURRENCY: 8
    restart: unless-stopped

volumes:
  redis-data:
